title: AI Data Science Interview Bot
emoji: 🎯
colorFrom: blue
colorTo: purple
sdk: gradio
sdk_version: 4.44.0
app_file: app.py
pinned: false
license: mit
tags:
- interview-practice
- data-science
- machine-learning
- career-development
- ai-feedback